# Generated by Django 4.2.23 on 2025-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coingecko_id", models.CharField(max_length=100, unique=True)),
                ("symbol", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                ("price_change_24h", models.FloatField(blank=True, null=True)),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
