# Generated by Django 4.2.23 on 2025-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_cryptocurrency_coingecko_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="symbol",
            field=models.CharField(max_length=128),
        ),
    ]
